# name: Linux Container Node Workflow

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - uses: azure/docker-login@v1
#       with:
#         login-server: chatbotchatgpt.azurecr.io
#         username: ${{ secrets.REGISTRY_USERNAME }}
#         password: ${{ secrets.REGISTRY_PASSWORD }}

#     - run: |
#         docker build . -t chatbotchatgpt.azurecr.io/bot:${{ github.sha }}
#         docker push chatbotchatgpt.azurecr.io/bot:${{ github.sha }}     

#     - uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'chatbot-chatgpt'
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         images: 'chatbotchatgpt.azurecr.io/bot:${{ github.sha }}'

on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/bot:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/bot:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/bot:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: chat-bot
            location: 'east asia'